Repository PyBotDevs/web, pull requests merged in 2022-12, with the labels that each got.

#1 Add custom Google fonts to webpage
  index.html
  style.css
Labels: enhancement, size/S

#2 Add NKA favicon as website shortcut icon
  index.html
Labels: enhancement, size/XS

#3 Add repository shortcut links to top navigation bar
  index.html
Labels: documentation, enhancement, size/XS

#4 Improve mobile web compatibility and accessibility features
  index.html
  style.css
Labels: documentation, enhancement, size/XS

#6 Add quick-action buttons for organization GitHub page and Discord server to website title panel
  index.html
  style.css
Labels: enhancement, size/S

#7 Add new cleaner design for website footer
  index.html
  style.css
Labels: enhancement, size/XS

#8 Add new underline accents to website section content
  index.html
  style.css
Labels: documentation, enhancement, size/S

#9 Debloat website main page
  index.html
Labels: size/M

#10 Debloated break tags in main website source code
  index.html
  palette.txt
Labels: enhancement, size/M, debloat

#11 Add social media referral icons in page footer
  index.html
  style.css
Labels: enhancement, size/S
